// console.log(Number("3.14"))
// console.log(Number(Math.PI))
// console.log(Number("bb"))
// console.log(Number(""))
// console.log(Number(" "))
// console.log(Number(true))
// console.log(Number(false))
// console.log(Number(null))
// console.log(Number(undefined))

// console.log(parseFloat("3.14"))
// console.log(parseFloat(Math.PI))
// console.log(parseFloat("bb"))
// console.log(parseFloat(""))
// console.log(parseFloat(" "))
// console.log(parseFloat(true))
// console.log(parseFloat(false))
// console.log(parseFloat(null))
// console.log(parseFloat(undefined))

// console.log(parseInt("3.14"))
// console.log(parseInt(Math.PI))
// console.log(parseInt("bb"))
// console.log(parseInt(""))
// console.log(parseInt(" "))
// console.log(parseInt(true))
// console.log(parseInt(false))
// console.log(parseInt(null))
// console.log(parseInt(undefined))

// console.log(+("3.14"))
// console.log(+(Math.PI))
// console.log(+("bb"))
// console.log(+(""))
// console.log(+(" "))
// console.log(+(true))
// console.log(+(false))
// console.log(+(null))
// console.log(+(undefined))

// console.log(Number(new Date()))
// console.log(parseFloat(new Date()))
// console.log(parseInt(new Date()))
// console.log(+(new Date()))

// console.log((1245).toString() + " " + typeof String(1245))
// console.log((true).toString())
// console.log((false).toString())
// console.log((new Date()).toString())
// console.log(([1,2,3,4]).toString())

// console.log(String(1245) + " " + typeof String(1245))
// console.log(String(true))
// console.log(String(false))
// console.log(String(new Date()))
// console.log(String([1,2,3,4]))


// console.log(1 + "5")
// console.log(1 - "5")
// console.log(3 * "5")
// console.log(1 / "5")
// console.log(1 + null)
// console.log("1" + null)
// console.log("3" * "5")

// console.log(Number([]))
// console.log(Number([10]))
// console.log(Number([10,20]))
// console.log(Number("twenty"))
// console.log(Number(function(){}))
// console.log(Number({}))

// console.log(String([]))
// console.log(String([10,20]))
// console.log(String(["ten","twenty"]))
// console.log(String(function(){}))
// console.log(String({}))
// console.log(String(null))
// console.log(String(undefined))


// console.log(Boolean(0))
// console.log(Boolean(1))
// console.log(Boolean(10))
// console.log(Boolean(-1))
// console.log(Boolean(-10))
// console.log(Boolean("0"))
// console.log(Boolean("0000"))
// console.log(Boolean("1"))
// console.log(Boolean(""))
// console.log(Boolean(" "))
// console.log(Boolean(NaN))
// console.log(Boolean(Infinity))
// console.log(Boolean("twenty"))
// console.log(Boolean([]))
// console.log(Boolean([10]))
// console.log(Boolean([10,20]))
// console.log(Boolean({}))
// console.log(Boolean(function(){}))
// console.log(Boolean(null))
// console.log(Boolean(undefined))